<a href="https://colab.research.google.com/github/Yaswanth-99/python/blob/master/28_06_19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
def test():
    print('Test() for function')
    return
test()

Test() for function


In [0]:
class Demo:
  def test(self):
      print("test() for class and method")
      return
   
obj = Demo()
obj.test()

test() for class and method


In [0]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact = 1
        while(n!=0):
             fact = fact*n;
             n = n - 1
        return fact
     
p1 = Demo1()
print(p1.fact(5))#120

120


In [0]:
class demo2:
  def accept(self,n1,n2):
    a=n1;
    b=n2;
    return;
  def display(self):
    print("a= ",a);
    print("b= ",b);
c1=demo2();
c1.display()

In [0]:
import numpy as np
lst={1,2,3,4,5}
array=np.array(lst);
print(array)

{1, 2, 3, 4, 5}


In [0]:
lst=(1,2,3,4)
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int64


In [0]:
#reshape trhe given array
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
a1=np.array([1,2,3])
a2=np.array([1,2,3])
print(np.hstack((a1,a2)))

[1 2 3 1 2 3]


In [0]:
a1=np.array([1,2,3])
a2=np.array([1,2,3])
print(np.vstack((a1,a2)))

[[1 2 3]
 [1 2 3]]


In [0]:
a1=np.random.normal(5,0.5,10)
print(a1)

[5.52512875 5.0517236  5.32790972 4.86929842 4.80469782 4.94242909
 5.36301625 5.44919138 4.59723092 5.11836241]


In [0]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [0]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [0]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [0]:
01                           